### ISSUE TITLE
Anzeige Fehler im Archiv

### ISSUE THREAD

**Issue by LaurinGrosse** [ThiebaudReimann/LEGOminati#2]
Im Archive unter 2021-22 wird nichts angezeigt, obwohl es genauso geschrieben ist wie bei den anderen, die funktionieren. Weder Name, Logo noch Beschreibung werden angezeigt.

Schaus dir bitte mal an.

Danke ;-)

**Comment by ThiebaudReimann** [comment]
Problem gefunden! die shortId wurde mit Leerzeichen geschrieben: "cargo connect"!
